### ISSUE TITLE
"Error: Done with no errors"

### ISSUE THREAD

**Issue by zilti** [jonase/eastwood#181] opened 2015-12-01 21:03 UTC
I always get this error when using eastwood in Emacs. IIRC this is the same bug that was around the last time I tried to use eastwood about a year ago?

![Eastwood error](http://i.imgur.com/jHiFvQg.png)

**Comment by jafingerhut** [comment] 2015-12-01 22:14
Looks like you are using Cider, and it is running Eastwood for you somehow?  I haven't used Cider, so don't know in what manner they are running Eastwood, what version of Eastwood they are using, and how they are choosing to print that error message.  Maybe try filing an issue with Cider, and refer to one of these issues from the other one to link them?

I'm happy to debug things if someone familiar with Cider can determine how that message appears, and determines that Eastwood is giving results that are wrong.

**Comment by jafingerhut** [comment] 2015-12-01 22:20
In the mean time, if you are using Leiningen, you can try running 'lein eastwood' in the root directory of your project and see what the output looks like.  If you are not using Leiningen, there are instructions to run Eastwood from a REPL in the Eastwood README.

**Comment by zilti** [comment] 2015-12-01 22:29
I'm using https://github.com/clojure-emacs/squiggly-clojure which in turn uses Eastwood, so maybe it's their fault?

**Comment by jafingerhut** [comment] 2015-12-01 22:48
I think it is worth at least showing them how to reproduce the issue with a particular project's files that you are able to share, and see if they can determine whether it is squiggly-clojure or Eastwood that seems to be the culprit.

**Comment by vemv** [comment] 2021-04-01 09:48
Looks like a good issue to be closed as it didn't show a problem with Eastwood itself.

Eastwood can always be used from a repl, lib, Lein, etc which can leave a more debuggable diagnostic.

Please don't hesitate creating issues in a future.

**Closed** 2021-04-01 09:49 UTC
