### ISSUE TITLE
:unused-ret-vals-in-try stack traces (and it should not)

### ISSUE THREAD

**Issue by philip-doctor** [jonase/eastwood#173] opened 2015-11-13 14:07 UTC
Here's the form in question:

````
(defn reconnecting-write
  [connect-fn prefix ^PrintWriter out rollup]
  (try
    (let [socket (if (and out (not (.checkError out)))
                   out
                   (do (IOUtils/closeQuietly out)
                       (connect-fn)))]
      (output prefix socket rollup (long (util/current-time))))
    (catch Exception e
      (IOUtils/closeQuietly out))))

````

I get a stack trace, not a linter warning
````
== Eastwood 0.2.1 Clojure 1.5.1 JVM 1.7.0_51
== Linting opsagent.metrics.graphite-reporter ==
Exception thrown by linter :unused-ret-vals-in-try on namespace opsagent.metrics.graphite-reporter
ClassCastException clojure.lang.PersistentArrayMap cannot be cast to java.lang.reflect.Method
	eastwood.passes/void-method? (passes.clj:66)
	eastwood.linters.unused/unused-ret-val-lint-result (unused.clj:390)
	eastwood.linters.unused/unused-ret-vals-2/iter--5441--5445/fn--5446/fn--5447 (unused.clj:519)
	eastwood.linters.unused/unused-ret-vals-2/iter--5441--5445/fn--5446 (unused.clj:481)
	clojure.lang.LazySeq.sval (LazySeq.java:42)
	clojure.lang.LazySeq.seq (LazySeq.java:60)
	clojure.lang.RT.seq (RT.java:484)
	clojure.core/seq (core.clj:133)
	clojure.core/filter/fn--4226 (core.clj:2523)
	clojure.lang.LazySeq.sval (LazySeq.java:42)
	clojure.lang.LazySeq.seq (LazySeq.java:67)
	clojure.lang.RT.seq (RT.java:484)
	clojure.core/seq (core.clj:133)
	eastwood.linters.unused/unused-ret-vals*/iter--5488--5492/fn--5493 (unused.clj:539)
	clojure.lang.LazySeq.sval (LazySeq.java:42)
	clojure.lang.LazySeq.seq (LazySeq.java:60)
	clojure.lang.RT.seq (RT.java:484)
	clojure.core/seq (core.clj:133)
	clojure.core/dorun (core.clj:2780)
	clojure.core/doall (core.clj:2796)
	eastwood.lint/lint-analyze-results (lint.clj:291)
	eastwood.lint/lint-ns (lint.clj:574)
	eastwood.lint/eastwood-core/fn--6329 (lint.clj:1041)
	eastwood.lint/eastwood-core (lint.clj:1040)
	eastwood.lint/eastwood (lint.clj:1154)
	eastwood.lint/eastwood-from-cmdline (lint.clj:1167)
	clojure.lang.Var.invoke (Var.java:415)
	eastwood.versioncheck/run-eastwood (versioncheck.clj:15)
	user/eval19 (form-init7437003406976767418.clj:1)
	clojure.lang.Compiler.eval (Compiler.java:6619)
	clojure.lang.Compiler.eval (Compiler.java:6609)
	clojure.lang.Compiler.load (Compiler.java:7064)
	clojure.lang.Compiler.loadFile (Compiler.java:7020)
	clojure.main/load-script (main.clj:294)
	clojure.main/init-opt (main.clj:299)
	clojure.main/initialize (main.clj:327)
	clojure.main/null-opt (main.clj:362)
	clojure.main/main (main.clj:440)
	clojure.lang.Var.invoke (Var.java:419)
	clojure.lang.Var.applyTo (Var.java:532)
	clojure.main.main (main.java:37)
== Warnings: 0 (not including reflection warnings)  Exceptions thrown: 1
````

it seems to be specifically dying on this

````
(do (IOUtils/closeQuietly out)
                       (connect-fn))
````

I don't think it should be erroring due to the having to side effect and ignore a nil return in the do, but if this really is a violation, it should be giving me a warning not a stack trace.

**Comment by jafingerhut** [comment] 2015-11-21 21:48
Is the code you are linting open source, and I could reproduce the failing case myself?  It would help in diagnosing the problem, and verifying whether I've fixed it.  I did a few minutes of searching via Google and GitHub, but am not sure which project this code appears in.

**Comment by philip-doctor** [comment] 2015-11-22 23:32
Hi Jafingerhut, unfortunately this is not an open source project.  I'll try to get this repro'd in a smaller project for you this week.  Thanks!

**Comment by philip-doctor** [comment] 2015-11-23 22:52
Here's a tiny demo project that repro's the issue:
https://github.com/philip-doctor/demo-linter-error

it took me a while to make it error, I found this:
````
  :dependencies [[org.clojure/clojure "1.5.1"]
                 [commons-io "2.4"]
                 ;[org.apache.commons/commons-io "1.3.2"]
                 ]
````


if I depend directly on org.apache.commons then the linter doesn't fail, but when I depend on commons-io, it fails.  So I think that while this will repro the error, the actual thing that's upsetting the linter might be in the underlying implementations of these libraries.

Thanks for taking a look at this :)

**Comment by jafingerhut** [comment] 2015-11-24 16:51
@philip-doctor Thanks for taking the time to create a demo project to reproduce the problem.

I have not determined why it happens when depending on one library but not the other, but I have determined the cause of the exception and changed Eastwood to avoid it.  It was not able to resolve the closeQuietly method call given an argument of type java.io.PrintWriter (it could if it was java.io.Writer, which PrintWriter is a subclass of), and that led to the exception.  I handle this case more quietly now -- just don't issue any warnings for a method call that Eastwood cannot resolve.

This fix will be in the next release of Eastwood.  I don't have a time frame scheduled for that next release yet, but if I keep the list of fixes fairly small, it could be December.

**Comment by jafingerhut** [comment] 2015-11-24 16:52
Fixed with commit https://github.com/jonase/eastwood/commit/48345f026ace78926eb9d51cc7ffc761b1227b77

**Closed by jafingerhut** 2015-11-24 16:52 UTC

**Comment by philip-doctor** [comment] 2015-11-24 17:02
Thanks for the fix :)
