### ISSUE TITLE
False positive on clojure spec?

### ISSUE THREAD

**Issue by didibus** [jonase/eastwood#227] opened 2017-08-24 23:15 UTC
There's some issues I think with Clojure spec:

`:linter :suspicious-expression, :msg "and called with 1 args. (and x) always returns x. Perhaps there are misplaced parentheses?"`

for

`(s/def :a/b (s/map-of :a/c (s/or :d? :a/b :string? string?)))`

AND

`:linter :constant-test, :msg "Test expression is always logical true or always logical false: 1 in form (if or__4469__auto__ or__4469__auto__ (clojure.core/or 0))"`

for

`(s/def :a/bb
  (s/map-of :a/cc :a/dd :min-count 1 :max-count 200 :distinct true))`

**Comment by jafingerhut** [comment] 2017-08-24 23:30
Thanks for the report.  I have not yet done any investigation into Clojure spec and how it interacts with Eastwood warnings, and I'm not aware of anyone else who has.  Not sure when/if it will be investigated.

**Comment by carocad** [comment] 2017-08-31 08:50
I am also having this issue. I have had to exclude the spec namespaces from being analyzed, otherwise eastwood reports an error on every compilation.

I check the code that was causing the problem and I am almost sure that the error is in `clojure.spec`. As you see from the expanded code, the spec macros dont fully resolve all conditions at compile time, leaving things like `or` and `and` to be evaluated in runtime even though the value is clear before hand as `eastwood` correctly reports.

I raised this topic once in the slack channel but didnt get much feedback on it. Probably because it was on the very early stage on Spec.

Hope it helps

**Comment by jafingerhut** [comment] 2017-08-31 09:08
It is reasonably common for macros to generate code in a way that a person would not write.  Because Eastwood expands macros before analyzing the code, it can generate warnings about these things.

Some Eastwood internal code has the ability to disable such warnings when they are caused by the expansion of particular macros.  For example, see this Eastwood source file: https://github.com/jonase/eastwood/blob/master/resource/eastwood/config/clojure.clj

or the other ones in this directory: https://github.com/jonase/eastwood/tree/master/resource/eastwood/config

It requires a bit of examination of the macro-expanded code to get a "filter" that minimizes the disabling of warnings possible -- too much and you might be risking disabling warnings about developer-written code included in the macro expansions.  I haven't tried to do that yet for clojure.spec macros, but if someone is interested in trying to create a 'filter' like the existing ones, and thinks they have found one that avoids at least the noisiest of false positive warnings, we can consider adding it to Eastwood.

**Comment by danielcompton** [comment] 2017-09-06 04:15
This could probably be tightened up a little bit, but it removes the warnings for me:

```
(disable-warning
  {:linter                      :suspicious-expression
   :for-macro                   'clojure.core/and
   :if-inside-macroexpansion-of #{'clojure.spec/every 'clojure.spec.alpha/every
                                  'clojure.spec/and 'clojure.spec.alpha/and}
   :within-depth                6
   :reason                      "Spec's macros generate one or more expressions for the and."})
```

**Comment by jafingerhut** [comment] 2017-09-06 04:26
@danielcompton Thanks for that.  Do you happen to know of an open source Clojure project that has one of these false positive warnings without your extra filter, and your filter eliminates the warning?

**Comment by danielcompton** [comment] 2017-09-06 04:48
I don't have an open source one, but these are what was triggering the warning:

```clj
(s/def :auth/roles (s/every keyword? :kind set?))

(def non-empty-string? (s/and
                         string?
                         (complement str/blank?)))
```

**Comment by danielcompton** [comment] 2017-09-06 04:55
Here's a sample project:

[eastwood-spec.zip](https://github.com/jonase/eastwood/files/1279813/eastwood-spec.zip)

```
lein eastwood "{:config-files [\"./eastwood.clj\"]}"
# vs
lein eastwood
```

**Comment by danielcompton** [comment] 2017-09-06 04:56
Even within-depth 1 works to eliminate the warnings:

```clj
(disable-warning
  {:linter                      :suspicious-expression
   :for-macro                   'clojure.core/and
   :if-inside-macroexpansion-of #{'clojure.spec/every 'clojure.spec.alpha/every
                                  'clojure.spec/and 'clojure.spec.alpha/and}
   :within-depth                1
   :reason                      "Spec's macros generate one or more expressions for the and."})
```

**Closed** 2017-10-10 22:36 UTC

**Comment by jafingerhut** [comment] 2017-10-10 22:37
The commit linked above adds the filter developed by @danielcompton to the default list of filters installed within Eastwood.  It should be in the next release.  Thanks, Daniel!

**Comment by carocad** [comment] 2018-01-17 09:29
@jafingerhut I am still having this issue even though I am using `eastwood 0.2.5`.

Some extra info
- [travis ci log when building](https://travis-ci.org/hiposfer/geojson.specs/builds/329788900?utm_source=github_status&utm_medium=notification)
- [github repo pointing at warning lines](https://github.com/hiposfer/geojson.specs/blob/eastwood/src/hiposfer/geojson/specs.cljc#L13)

hope it helps

**Comment by slipset** [comment] 2018-01-25 21:09
`s/keys` with only `opt-un` seems to break as well:
```clojure
(macroexpand '(s/keys :opt-un [::created-by ::createdByName ::createdByEmail]))
;; => (clojure.spec.alpha/map-spec-impl
 {:req-un 'nil,
  :opt-un
  '[:ardoq.specs/created-by
    :ardoq.specs/createdByName
    :ardoq.specs/createdByEmail],
  :gfn nil,
  :pred-exprs [(fn* [G__163116] (clojure.core/map? G__163116))],
  :keys-pred
  (fn* [G__163116] (clojure.core/and (clojure.core/map? G__163116))),
  :opt-keys '[:created-by :createdByName :createdByEmail],
  :req-specs '[],
  :req 'nil,
  :req-keys '[],
  :opt-specs
  '[:ardoq.specs/created-by
    :ardoq.specs/createdByName
    :ardoq.specs/createdByEmail],
  :pred-forms '[(clojure.core/fn [%] (clojure.core/map? %))],
  :opt 'nil})```

```clojure
(disable-warning
  {:linter                      :suspicious-expression
   :for-macro                   'clojure.core/and
   :if-inside-macroexpansion-of #{'clojure.spec/every 'clojure.spec.alpha/every
                                  'clojure.spec/and 'clojure.spec.alpha/and
                                  'clojure.spec/keys 'clojure.spec.alpha/keys
                                  }
   :within-depth                3
   :reason                      "Spec's macros generate one or more expressions for the and."})
```
solves it.
