### ISSUE TITLE
wrong-tag-keys=#{:eastwood/o-tag :eastwood/tag}

### ISSUE THREAD

**Issue by jgeraerts** [jonase/eastwood#184] opened 2015-12-17 11:49 UTC
When running eastwood on my imageresizer code ( https://github.com/jgeraerts/imageresizer ) i get following thing dumped.

**Comment by jgeraerts** [comment] 2015-12-17 11:52
[eastwood.txt](https://github.com/jonase/eastwood/files/65319/eastwood.txt)

**Comment by jafingerhut** [comment] 2015-12-17 18:52
Looks like you have hit a new case in tools.analyzer.jvm resolving type tags for analyzed code than I've seen in my Eastwood testing before.  Glad that it is on an open source project -- I've confirmed I get the same error when I try linting that project on my machine, which should help in fixing it, and verifying I've fixed it.  Thanks for the new test case!

**Comment by vemv** [comment] 2021-06-03 08:52
As of `master` today (https://github.com/jgeraerts/imageresizer/tree/43cb7c1e4c8ff6772e8f11ac5766c413187a3059), `lein eastwood` doesn't print an extraneous thing anymore.

It completes without any stacktrace or false positive:

<details>

```
~/imageresizer (master) $ lein eastwood
== Eastwood 0.4.2 Clojure 1.8.0 JVM 1.8.0_282 ==
Directories scanned for source files:

dev src test
== Linting net.umask.imageresizer.source ==
== Linting net.umask.imageresizer.util ==
== Linting net.umask.imageresizer.urlparser ==
== Linting net.umask.imageresizer.expires ==
== Linting net.umask.imageresizer.bufferedimage ==
== Linting net.umask.imageresizer.graphics ==
== Linting net.umask.imageresizer.image ==
== Linting net.umask.imageresizer.cache ==
== Linting net.umask.imageresizer.httpsource ==
== Linting net.umask.imageresizer.nio ==
== Linting net.umask.imageresizer.filestore ==
== Linting net.umask.imageresizer.checksum ==
== Linting net.umask.imageresizer.s3store ==
== Linting net.umask.imageresizer.watermark ==
== Linting net.umask.imageresizer.bytebuffer ==
== Linting net.umask.imageresizer.resizer ==
== Linting net.umask.imageresizer.config ==
== Linting net.umask.imageresizer.vhost ==
== Linting net.umask.imageresizer.server ==
== Linting net.umask.imageresizer ==
== Linting net.umask.imageresizer.exceptions ==
== Linting net.umask.imageresizer.memorystore ==
== Linting user ==
dev/user.clj:38:3: deprecations: Instance method 'public void java.awt.Window.show()' is deprecated.
== Linting net.umask.imageresizer.expires-test ==
== Linting net.umask.imageresizer.urlparser_test ==
== Linting net.umask.imageresizer.testutils ==
== Linting net.umask.imageresizer.watermark-test ==
test/net/umask/imageresizer/watermark_test.clj:13:29: Reflection warning - call to method getRGB can't be resolved (target class is unknown).
test/net/umask/imageresizer/watermark_test.clj:13:29: Reflection warning - call to method getRGB can't be resolved (target class is unknown).
== Linting net.umask.imageresizer.vhost_test ==
== Linting net.umask.imageresizer.checksum-test ==
== Linting net.umask.imageresizer.cache-test ==
== Linting net.umask.imageresizer.config_test ==
== Linting net.umask.imageresizer.image-test ==
== Linting net.umask.imageresizer.filestore_test ==
test/net/umask/imageresizer/filestore_test.clj:15:67: Reflection warning - call to static method alength on clojure.lang.RT can't be resolved (argument types: unknown).
test/net/umask/imageresizer/filestore_test.clj:29:33: Reflection warning - reference to field toString can't be resolved.
test/net/umask/imageresizer/filestore_test.clj:39:35: Reflection warning - reference to field toString can't be resolved.
== Linting net.umask.imageresizer.resizer-test ==
test/net/umask/imageresizer/resizer_test.clj:70:21: Reflection warning - call to method getRGB can't be resolved (target class is unknown).
test/net/umask/imageresizer/resizer_test.clj:70:21: Reflection warning - call to method getRGB can't be resolved (target class is unknown).
== Linting done in 4835 ms ==
== Warnings: 1 (not including reflection warnings)  Exceptions thrown: 0
Subprocess failed (exit code: 1)
```

</details>

**Closed by vemv** 2021-06-03 08:52 UTC
