### ISSUE TITLE
No useful description when reader exception occurs

### ISSUE THREAD

**Issue by qezz** [jonase/eastwood#319] opened 2019-04-28 10:50 UTC
I was trying to use eastwood against riemann, but getting the following error:

```
$ lein eastwood
== Eastwood 0.3.5 Clojure 1.10.0 JVM 1.8.0_181 ==
Unknown error: {:type :reader-exception, :ex-kind :reader-error}
Subprocess failed
```

It seems like the exception occurs when there is an unescaped backslash in the ns docstring.

Here is a small project to reproduce: https://github.com/qezz/eastwood-reader-exception

```clojure
;; core.clj
(ns eastwood-reader-exception.core
  "/--- ---\
   hello world")
```

I hope there should be a bit more helpful explanation of what was happened.

Thanks

**Comment by slipset** [comment] 2020-01-06 20:57
What a coincidence https://github.com/riemann/riemann/commit/75f97d2f3af347aa2b01396adb131a2e858e4184
But yes, this should be fixed

**Comment by vemv** [comment] 2021-04-01 09:25
> But yes, this should be fixed

Indeed :)

I tried this issue the other day and it cannot reproduce it - I get a perfectly informative stacktrace

Proposing to close

**Closed** 2021-04-01 09:29 UTC
