### ISSUE TITLE
Check consistency of namespace and file names

### ISSUE THREAD

**Issue by sooheon** [jonase/eastwood#305] opened 2018-12-19 16:46 UTC
Using deps.edn:

```
{:paths ["src/main" "src/test" "resources"]
 ...}
```

And I have files such as "src/main/acme/core.clj" with namespace `acme.core`, which eastwood complains should actually be named `main.acme.core`. Cursive respects the namespace beginning at the "src/main" directory, why does eastwood not?

**Comment by jafingerhut** [comment] 2018-12-19 18:07
I have not dug into the root cause here yet, but I have a guess -- The code paths for when Eastwood is started from Leiningen are well tested and documented in Eastwood's README, in terms of how the contents of Leiningen $HOME/.lein/profiles.clj file contents, the project's project.clj file contents, and the command line contents are merged together to form the final options to Eastwood.

The code paths for starting Eastwood via `clj` with a deps.edn file are not so thoroughly documented yet.  I suspect that the `:paths` key in the deps.edn file is being ignored when calculating what the options to Eastwood are, and thus Eastwood is receiving the default `"src"` directory for the `:source-paths` key, not `"src/main"` as you might wish in your case.

This is almost certainly possible to improve in Eastwood, with a little time and attention paid to where all of the data comes from in `deps.edn`, and how that flows through Eastwood's init code.

**Comment by vemv** [comment] 2022-01-09 01:15
These days, Eastwood auto-infers :source-paths / :test-paths very accurately for deps.edn projects.

Anyway, deps.edn setup is documented in https://github.com/jonase/eastwood/tree/b6cf5e67dec600b7368db012c868103fe8a314ba#depsedn

In particular, the `{}` in `:main-opts ["-m" "eastwood.lint" {}` is a config map, which could be instead e.g.:

```
{:source-paths ["src/main"]
 :test-paths ["src/test"]
 ;; https://github.com/jonase/eastwood/tree/b6cf5e67dec600b7368db012c868103fe8a314ba#ignored-faults
 :ignored-faults {:reflection {some.example.ns true}}}
```

**Closed by vemv** 2022-01-09 01:15 UTC
